### ISSUE TITLE
Camp screen question

### ISSUE THREAD

**Issue by Reiska42** [snafaru/Wizardry.Code#4]
Is it possible to update the character sheet screen in camp to also update when you trade gold or heal HP, the way it now updates when an item breaks, or is there not code space for it?

(Actually, as an extension of that, is there code space to add pool/divvy gold functions like are seen in the later Wizardry ports?)

**Comment by snafaru** [comment]
Hi.

 

#1: Concerning camp screen refresh for gold, and cure HP. Putting this on the list of things to improve.

 

#2: Concerning divvy gold. This is a major one in terms of coding space required. At the moment the disk is completely full. I am looking at making Wizardry work on Pascal v1.3 in order to take advantage of having the capability to have 800K disk space instead of only 140K at the moment. Preliminary tests with Pascal 1.3 (at least 40 hours in already) were that I was able to construct a build that runs in two emulators (Apple IIgs in KEGS and MAME) and on a real Apple II GS with a floppy in 3.5” floppy in slot 5 but with severe hurdles getting in the way (Pascal v1.3 scanning for slot 6 disks whether they be there or not is one of them). Making Wizardry work properly in Pascal 1.3 using 3.5” 800K disks will be a year-long project at least. Calling the community here for anyone who would have the special Pascal v1.3 runtime version and tools disks, they could be awfully useful. Also, if a coding guru has the heart in themselves to have AppleWin handle 3.5” disks, that would be something.

**Comment by snafaru** [comment]
#1: Fixed in Release 09 Apr 2023. Added code to display on the fly Gold, Hit Points, and Status updates of the character who is on screen when trading gold or casting spells to heal hit points or ailments. This works while using potions as well.

#2: Divvy Gold, and Pool Gold are future projects since there is not code space on the disk. See answer above regarding Pascal v1.3 and bigger disks.
