### ISSUE TITLE
Credit to Tom Ewers missing?

### ISSUE THREAD

**Issue by TommyGH** [snafaru/Wizardry.Code#5]
My name is Tom Ewers.  Back around 2012 and 2014 I converted the AppleII Wizardry disks into Pascal "source" code.  If you used this information to build this code, could you at least please give me credit in the Readme?  I spent literally thousands of hours to create the Pascal code, and hundreds of hours documenting my efforts in the AppleII newsgroups:  "Re-engineered: Wizardry III, Legacy of Llylgamyn" and "Wizardry re-engineering" -- for Wizardry I, Proving Grounds.

I recently saw an interview on Matt Barton's YouTube channel, where 2 people talk about how they remastered Wizardry I, Proving Grounds.   They also seemed to ignore where the original Pascal code likely came from.

**Comment by snafaru** [comment]
Hello Thomas.I will gladly add it. I am not sure why/how I missed it there because I have added it at the beginning of every text files within that site already.I just started a 3-weeks vacation and I am out the country away from my tools and passwords so I must ask for your patience, I am putting this as the very first thing to do on my tasks list upon my return on the 14th of July.Thanks for letting me know about this, I am all for giving credit where credit is due.
    Eric
  

 From: TommyGH ***@***.***>Sent: Monday, June 24, 2024 01:26To: snafaru/Wizardry.Code ***@***.***>Cc: Subscribed ***@***.***>Subject: [snafaru/Wizardry.Code] Credit to Tom Ewers missing? (Issue #5) 
My name is Tom Ewers.  Back around 2012 and 2014 I converted the AppleII Wizardry disks into Pascal "source" code.  If you used this information to build this code, could you at least please give me credit in the Readme?  I spent literally thousands of hours to create the Pascal code, and hundreds of hours documenting my efforts in the AppleII newsgroups:  "Re-engineered: Wizardry III, Legacy of Llylgamyn" and "Wizardry re-engineering" -- for Wizardry I, Proving Grounds.
I recently saw an interview on Matt Barton's YouTube channel, where 2 people talk about how they remastered Wizardry I, Proving Grounds.   They also seemed to ignore where the original Pascal code likely came from.

**Comment by snafaru** [comment]
Hi Thomas. I have updated the main page README. Note that the text files for each fix already included the credits for you. I went through all my pages and web site thoroughly to make sure credit was given. If you find I missed giving credit somewhere else, let me know and I will gladly add it. Again my apologies for missing it on this Github's main page README, it was just a human oversight.
